// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection

[<assembly:AssemblyTitleAttribute("FluidTypes")>]
[<assembly:AssemblyProductAttribute("FluidTypes")>]
[<assembly:AssemblyDescriptionAttribute("A refinement type library for F#")>]
[<assembly:AssemblyVersionAttribute("0.0.1")>]
[<assembly:AssemblyFileVersionAttribute("0.0.1")>]
[<assembly:AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    [<Literal>]
    let AssemblyTitle = "FluidTypes"

    [<Literal>]
    let AssemblyProduct = "FluidTypes"

    [<Literal>]
    let AssemblyDescription = "A refinement type library for F#"

    [<Literal>]
    let AssemblyVersion = "0.0.1"

    [<Literal>]
    let AssemblyFileVersion = "0.0.1"

    [<Literal>]
    let AssemblyConfiguration = "Release"
