version: 2
jobs:
  build:
    docker:
      - image: fangyizhou/fluidtypes

    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-{{ checksum "paket.lock" }}
            - deps-

      - run:
          name: Restore dependencies
          command: nuget restore

      - run:
          name: Build
          command: |
            dotnet build

      - run:
          name: Test
          command: |
            dotnet test


      - save_cache:
          key: deps-{{ checksum "paket.lock" }}
          paths:
            - packages
