version: 2
jobs:
  build:
    docker:
      - image: fsharp

    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-{{ checksum "paket.dependencies" }}
            - deps-

      - run:
          name: Restore dependencies
          command: mono .paket/paket.exe restore

      - run:
          name: Build
          command: msbuild

      - save_cache:
          key: deps-{{ checksum "paket.dependencies" }}
          paths:
            - packages
            - paket-files
