version: 2
jobs:
  build:
    docker:
      - image: fangyizhou/fluidtypes

    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-{{ checksum "paket.lock" }}
            - deps-

      - run:
          name: Build and Test
          command: ./build.sh

      - save_cache:
          key: deps-{{ checksum "paket.lock" }}
          paths:
            - packages
