version: 2
jobs:
  build:
    docker:
      - image: fangyizhou/fluidtypes

    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-{{ checksum "Fluid/packages.config" }}
            - deps-

      - run:
          name: Restore dependencies
          command: nuget restore

      - run:
          name: Build
          command: msbuild

      - run:
          name: Test
          command: |
            curl -L -O https://raw.githubusercontent.com/nunit/nunit-transforms/master/nunit3-junit/nunit3-junit.xslt
            mkdir junit
            mono packages/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe FluidTest/FluidTest.fsproj --result=junit/junit.xml\;transform=nunit3-junit.xslt

      - store_test_results:
          path: junit

      - save_cache:
          key: deps-{{ checksum "Fluid/packages.config" }}
          paths:
            - packages
