version: 2
jobs:
  build:
    docker:
      - image: fsharp

    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-{{ checksum "Fluid/packages.config" }}
            - deps-

      - run:
          name: Restore dependencies
          command: nuget restore

      - run:
          name: Build
          command: msbuild

      - save_cache:
          key: deps-{{ checksum "Fluid/packages.config" }}
          paths:
            - packages
