// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FluidTypesConsole")>]
[<assembly: AssemblyProductAttribute("FluidTypes")>]
[<assembly: AssemblyDescriptionAttribute("A refinement type library for F#")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FluidTypesConsole"
    let [<Literal>] AssemblyProduct = "FluidTypes"
    let [<Literal>] AssemblyDescription = "A refinement type library for F#"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
